### ISSUE TITLE
Automatic Nuget download fails

### ISSUE THREAD

**Issue by vladzaharia** [JoshuaKGoldberg/TSLint.MSBuild#52]
Trying to run the NuGet exe that gets downloaded automatically results in a SmartScreen error 
![SmartScreen error](https://cloud.githubusercontent.com/assets/79390/20226733/19798afe-a7fe-11e6-964e-6619f5b90877.png) and the running `gulp` results in

```[11:01:20] Using gulpfile D:\tslint.msbuild2\gulpfile.js
[11:01:20] Starting 'test'...
[11:01:20] Starting 'test:TSLintArgs'...
[11:01:21] Starting 'nuget-download'...
[11:01:21] Finished 'nuget-download' after 376 μs
[11:01:21] Starting 'nuget-pack'...
internal/child_process.js:302
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at exports._errnoException (util.js:953:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:372:9)
    at Object.exports.execFile (child_process.js:139:15)
    at D:\tslint.msbuild2\node_modules\gulp-nuget\lib\pack.js:28:10
    at D:\tslint.msbuild2\node_modules\gulp-nuget\node_modules\fs-extra\lib\mkdirs\mkdirs.js:47:16
    at FSReqWrap.oncomplete (fs.js:117:15)```
```
The file seems to be 0 bytes, so it indicates that the download probably failed.

**Comment by JoshuaKGoldberg** [comment]
I couldn't repro the 0-size file so it must have been a permissions error. The `nuget-download` task will now check for it and complain if it sees this problem.
